name: Build Windows64

on:
  push:
    tags: [build*]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install msbuild # https://github.com/microsoft/setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Compile main.cpp
        run: |
          cl main.cpp /Fe:main.exe   # Fe - name of output file
        shell: cmd # Použijeme 'cmd' shell, což je pro Windows často nejlepší pro MSVC příkazy

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-exe
          path: main.exe